### PR TITLE
fix: add episode to search when using imdbid search

### PR DESCRIPTION
**Pull request by kobik**

### CODE REVIEW

**Comment by bakerboy448** [comment]
Should this also include season in addition to episode?

also tested to confirm it works?

**Comment by kobik** [comment]
Shouldn't .Query.Episode include the full SxxExx string?
At least that's what I see in prowalarr logs when doing a search from sonarr.

**Comment by bakerboy448** [comment]
Pretty sure Query.Episode is literally just the episode; hence why season exists

**Comment by kobik** [comment]
There is also `.Query.Ep`, while according to the docs `.Query.Episode` is
> EpisodeSearchString, such as S00E00 or S00 or yyyy.MM.dd

additionally, here is how the relevant log lines from prowlarr with this change
```
[Info] ReleaseSearchService: Searching indexer(s): [Hebits] for Term: [] | ID(s): IMDbId:[11126994] for Season / Episode:[S01E01], Offset: 0, Limit: 100, Categories: [5000]
https://hebits.net/torrents.php?searchstr=tt11126994+S01E01&order_by=time&order_way=desc&filter_cat[2]=1
```

**Review by bakerboy448 — APPROVED** [review]

**Pull request merged**
