### PR TITLE
fix: login at bittorrentfiles (#666)

### PR DESCRIPTION
**Pull request by imba3r**
This change got previously merged with PR #127, but somehow it got lost a couple of weeks ago.
The issue in prowlarr was/is https://github.com/Prowlarr/Prowlarr/issues/666.

Closes https://github.com/Prowlarr/Prowlarr/issues/1110

### CODE REVIEW

**Comment by bakerboy448** [comment]
Jackett still has forms.  Does jackett need to be changed to post as well?  If not, then this isn't the best/proper fix.

**Comment by ilike2burnthing** [comment]
@garfield69 is login/reconfiguring failing for you for bittorrentfiles? Does this resolve it?

**Comment by garfield69** [comment]
@ilike2burnthing  the Jackett bittorrentfiles indexer is working for me using both the config/save and TEST.
The choice to use the post method or the form method for a login page usually comes down to whether or not there are additional login challenges on the login page that may show up when a user has previously failed to login.
Example: a post to the takelogin.php would not work if the user failed a prior login and the sites login.php is now showing an additional simple catpcha.
With regards to Bittorrentfiles I see that it was an indexer submitted way back in Jan 2018 by a non-member contributor and has always used the form method. For a slight performance boost we could switch to using the post method if we wanted.

**Comment by ilike2burnthing** [comment]
Yea, if it's causing an issue here then we might as well. I'll do that now, as I need to update the readme anyway,

**Comment by Qstick** [comment]
Fixed in https://github.com/Prowlarr/Indexers/commit/851aedb41cea063a302551bf5868ec5e94118525

Thanks

**Pull request closed without merging**
