### PR TITLE
Allow RawSearch for Nyaa.si

### PR DESCRIPTION
**Pull request by EccentricVamp**
I followed the hint in https://github.com/Prowlarr/Indexers/issues/186#issuecomment-1120088887. It was marked as help wanted. I'm not really sure what the pull request process is on this repo, so I'm just gonna go for it.

I tested it on my machine. Manually modified the local definition of nyaasi.yml, forced Prowlarr to update its indexer definitions, confirmed the changes, and searched a few movies via Radarr. Everything worked fine.

I also tested a few searches that were returning 0 results before the change due to apostrophes and other characters being stripped. This change did fix those searches.

I don't know the ramifications of allowing RawSearch, so some additional testing/review would be appreciated.

### CODE REVIEW

**Comment by bakerboy448** [comment]
V3 not v2 please

But yeah testing and ensuring it's consistent is the main issue

**Comment by EccentricVamp** [comment]
Ooops. I didn't understand the versioning very clearly. Just managed to hunt down the line in the wiki about no more modifications to v2. Might be a good idea to add that to the readme for the repo. I've moved the changes to v3.

Are there any previous examples or edge cases where RawSearch caused unexpected behavior? I'd be happy to do the testing myself.

**Comment by bakerboy448** [comment]
There's a PR to update the readme 😩.

Probably just run through as much anime that has special characters that would get replaced with a ` ` in it as possible...or compare to what Sonarr itself does for native Nyaa perhaps. (Not sure if that's better or not)

**Comment by EccentricVamp** [comment]
I was never able to get Nyaa.si working natively with Sonarr. I've used Jackett in the past, but it didn't support RawSearch either. So I can't use either of those for comparison.

I've decided to start testing it with some entries from the Gundam series. There's enough apostrophes and colons and other special characters that it should be an okay test. If that works, I'll try to hunt down some tricker edge cases.

Is there an easy way to make my manual changes to the local definitions stick? I just changed it yesterday but the indexer definition update has already overwritten those changes and I don't see any way to stop it.

**Comment by bakerboy448** [comment]
The definitions are overwrote and refreshed daily. Your local changes absolutely should not be there. The file should be overwrote.

Use a custom definition. The id and filename must me unique.
https://wiki.servarr.com/prowlarr/indexers#adding-a-custom-yml-definition

**Comment by EccentricVamp** [comment]
Thanks for the tip. I've downloaded a couple seasons now with no issues.

**Comment by EccentricVamp** [comment]
Okay, did some more comprehensive testing.

These worked (accurate results)
- Japanese titles with a bunch of Kanji in them
- All the Gundam titles with colons and dashes in them

These didn't work (inaccurate results)
- ∀ Gundam

    Tried this with and without Kanji, but couldn't get good results. This may be due to the fact that most of the torrents on Nyaa.si use the spelled out anglicized form (Turn A Gundam).

**Comment by bakerboy448** [comment]
Bump to v4, but otherwise has this been going well?

**Comment by EccentricVamp** [comment]
Yep, I've grabbed several more shows and a few movies now with no issues.

**Review by bakerboy448 — APPROVED** [review]

**Pull request merged**
