### PR TITLE
Create bjshare.yml

### PR DESCRIPTION
**Pull request by HugoFM2**
Add private Brazilian tracker bj-share to indexers

### CODE REVIEW

**Comment by bakerboy448** [comment]
What makes this a v2 indexer and not a v1?

**Comment by Qstick** [comment]
Because of the parser changes it's impossible to tell what will work new with v2 vs v1 based on the yml alone. Anything new should go to v2 so I think this PR is fine.

**Comment by HugoFM2** [comment]
When I started coding this indexer I was using optional selectors, but I prefered to change to if eq Template and forgot to move the file to v1. 
Now, like @Qstick said and the new PR in Readme.md, I think it's okay to leave the file on v2 folder.
I changed the errors in the test to meet the requeriments too.

**Comment by Qstick** [comment]
@garfield69 Any reason not to have bjshare as yml vs the Jackett C# implementation?

**Comment by garfield69** [comment]
>Any reason not to have bjshare as yml vs the Jackett C# implementation?

Looking at its Jackett history, its one of the oldest indexer, written by the founding owner of Jackett, kaso17, back on Oct 2016.
At first I thought it might have preceded the merging of Cardigann into Jackett, but that is not the case. 

Looking at the C# code, (and accepting that I am not a C# dev so my code reading may be faulty), it looks to me like the web site has search results rows that can consist of groups rather than single torrent entries.
If you can confirm this that would be useful to know for certain.

The current Jackett Cardigann can only handle a one-title-one-torrent layout, so it does not have the logic to handle a one-title-group that consist  of multiple related torrents with a common single details page and no individual title of their own.

No one on the current Jackett team has an account on the site, so I cannot take a look at the web site myself and see if there  is an account profile option that turns off grouping, as some other sites provide.

**Comment by Qstick** [comment]
@HugoFM2 any chance you can spot us an invite to test things?

**Comment by VozDeOuro** [comment]
@Qstick mybe i can help test it dm me :)

**Comment by VozDeOuro** [comment]
Any news ?

**Comment by Qstick** [comment]
> Any news ?

Need confirmation on categories list. Doesn't seem many were included with this PR

**Comment by uilton-oliveira** [comment]
> > Any reason not to have bjshare as yml vs the Jackett C# implementation?
> 
> Looking at its Jackett history, its one of the oldest indexer, written by the founding owner of Jackett, kaso17, back on Oct 2016. At first I thought it might have preceded the merging of Cardigann into Jackett, but that is not the case.
> 
> Looking at the C# code, (and accepting that I am not a C# dev so my code reading may be faulty), it looks to me like the web site has search results rows that can consist of groups rather than single torrent entries. If you can confirm this that would be useful to know for certain.
> 
> The current Jackett Cardigann can only handle a one-title-one-torrent layout, so it does not have the logic to handle a one-title-group that consist of multiple related torrents with a common single details page and no individual title of their own.
> 
> No one on the current Jackett team has an account on the site, so I cannot take a look at the web site myself and see if there is an account profile option that turns off grouping, as some other sites provide.

Hello, i'm one of the contributors of BJ-Share indexer on Jackett, and you're right, there's a setting that you can toggle between group torrents or not, so you have to consider both cases..

image

With grouping enabled:
image
image

With it disabled:
image

**Comment by uilton-oliveira** [comment]
Also, the releases of this tracker nos not that consistent... for anime for exemple, most of it is in absolute episode numbering (but with season also included), but some are relative to season... so there's some hacks also to make it compatible with sonarr/radarr

**Comment by HugoFM2** [comment]
- I changed the code to gather the remaining categories (some of them has changed and some of them has been removed since the jackett code)
 - I tried to fix the Single torrent/ group torrent identification, without the need to change the "group enable" option as @uilton-oliveira described, maybe his approach is a better one
 - As @uilton-oliveira said, there's some categories that are not consistent, mainly animes. For this, I tried to code following the most recent releases, that follows episode numbering with season (SXXEXX), but for old ones, like one piece, there's no fix for them, as it follows absolute numbering (S15E880, as example). 
 - I tested every category and compared  with jackett / BJ-Share results, and all of them work as expected. I also tested with Sonarr and Radarr and both of them worked and get the same valid results as jackett
 - @Qstick sorry but I don't have enough points to give you an invite (I need 12.600.00 points and I have 5.286.178), I'll try to seed more torrents to get one

**Comment by VozDeOuro** [comment]
how can i test it on prowlarr ?

**Comment by bakerboy448** [comment]
> how can i test it on prowlarr ?

https://wiki.servarr.com/prowlarr/indexers#adding-a-custom-yml-definition

**Review by Qstick — APPROVED** [review]

**Comment by VozDeOuro** [comment]
they recently put some "I'am not a robot" test on the login page 
image

**Comment by VozDeOuro** [comment]
hey @HugoFM2 
are you having problems with bj tracker lately?
can you send me a PM on discord pls ?!
Voz De Ouro#2311

**Pull request merged**
