### PR TITLE
schema: add htmldecode & htmlencode

### PR DESCRIPTION
**Pull request by ilike2burnthing**
#### Indexer/Tracker
v7 schema

#### Description
From https://github.com/Jackett/Jackett/commit/40e98be02a00ccd84f20aa57880c8425b9d4f558 for https://github.com/Jackett/Jackett/commit/17c1a19ef54dd326e4c312985f1860151c71e8f0 and https://github.com/Jackett/Jackett/pull/13906.

Needed for https://github.com/Prowlarr/Prowlarr/pull/1331 and the next Jackett Cardigann indexer merge.

#### Issues Fixed or Closed by this PR
N/A

### CODE REVIEW

**Comment by bakerboy448** [comment]
This should really be a version bump as prior prowlarr versions will error out and cannot use v7 definitions that have this added.

**Comment by ilike2burnthing** [comment]
Better left for https://github.com/Prowlarr/Indexers/pull/241 then?

**Comment by bakerboy448** [comment]
#241 will need its usual bump to the next version then, don't believe it's landing anytime soon

**Comment by ilike2burnthing** [comment]
cartoonchaos, thesceneplace, hqmusic, and possibly anthelion-api will all need held back from any future merges until then.

This can be closed as unneeded, or left open as a reminder, whatever is best.

**Comment by bakerboy448** [comment]
They'll error out as in not work or have that site with the new features not work as expected for all older prowlarr versions - same as any/all other Cardigann net new items.

the sync script will pull the new defs over and bump them to v8 as they'd fail to match the v7 schema

**Pull request closed without merging**
