### PR TITLE
NewHeaven Indexer

### PR DESCRIPTION
**Pull request by Bretterteig**
#### Indexer/Tracker
NewHeaven (Torrent Heaven Resurrection)

#### Description
There is a jackett version of this that does not work. 
Uses cookie as I did not find a workaround to handle redirects (which in this case are expected)

Supports all field types that new heaven offers.
Queries are currently limited to 25 per search as pagination size is hardcoded.

### CODE REVIEW

**Comment by bakerboy448** [comment]
Should be done upstream in jackett

cc @ilike2burnthing @garfield69

**Comment by garfield69** [comment]
None of the Jackett team have an account so we cannot independently test/verify.

The Jackett indexer is written in C# so we would be happy to migrate to yaml.

However, while this PR is reported as working, it will not pass the yaml schema validation, and likely will also be generating many errors/warnings in the log (in either the regular or the debug logs, with missing categories, and date mismatch) so its needs a little finessing.

I will port this to Jackett, and apply our standards on it, (dropping options, simplifying selectors, adding missing categories, etc).
but since I cannot test it, we will need to rely on the OP to confirm it still works and report back issues.
Jackett Ticket https://github.com/Jackett/Jackett/issues/15527

**Comment by bakerboy448** [comment]
Preciate it

**Comment by garfield69** [comment]
Jackett v0.22.425 for newheaven first release. Untested, may need updates. Please report issues at https://github.com/Jackett/Jackett/issues/15527

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/5d7328118b0b6020fe544f34d79b125a20d13aaa

**Pull request closed without merging**
