### PR TITLE
New: (Indexers) (MoreThanTV) Add standard + 2FA

### PR DESCRIPTION
**Pull request by ntldr0**

### CODE REVIEW

**Review by bakerboy448 — CHANGES_REQUESTED** [review]
These should be v1 not V2 given they do not have usage of the download selectors 

defer to Q on the YML

Looks like Jackett has only had this as C#?
https://github.com/Jackett/Jackett/blob/aca4a16baeabacffc9e322eb91c3a511e7da0ba3/src/Jackett.Common/Indexers/MoreThanTV.cs

I assume the following have been tested:
- [ ] Sonarr standard episode search
- [ ] Sonarr daily episode search
- [ ] Sonarr season pack search 
- [ ] Radarr movie search

**Comment by ntldr0** [comment]
> These should be v1 not V2 given they do not have usage of the download selectors

Would it be better to properly implement it as v2 or just move these to the v1 folder?

> Looks like Jackett has only had this as C#?

Correct, but Jackett already has problems with MTV.  I found this issue: https://github.com/Jackett/Jackett/issues/9670 and figured it seemed like moving forward, it's best if MTV is implemented as a Cardigann yml.

> I assume the following have been tested:

I have only tested Radarr movie search so far.  I will update you when I have tested the various Sonarr searches.

**Comment by bakerboy448** [comment]
Given v2 indexers are not yet supported by Prowlarr, likely not.

have you found a work around for [this comment](https://github.com/Jackett/Jackett/issues/9670#issuecomment-780237199)?

**Comment by austinwbest** [comment]
> Just a bump

I can't test it, need someone with MTV to test

**Comment by russelg** [comment]
I've tried testing this, and due to the [comment as previously linked](https://github.com/Jackett/Jackett/issues/9670#issuecomment-780237199), releases will not show as expected.

Here is what I get for the show "Mr Robot" in Prowlarr:
image
Results like this will lead to nothing being detected in Sonarr/Radarr.

Here is what the linked torrent for season 1 displays:
image
And how the search result appears for that season:
image


Not sure what can be done about this. The way MTV presents individual torrents is quite awful.

**Comment by ntldr0** [comment]
Based on conversations with staff, the torrent search page is currently under development (example: I don't think torrent grouping was enabled at the time of me submitting this PR).  There are plans to add API support in the future.  So I think it doesn't make sense to put any more work towards these changes until API support is added (or at least changes to the torrent search page have slowed down).

Thanks to everyone that reviewed and/or tested these changes though!

Closing PR for now.

**Pull request closed without merging**
