### PR TITLE
cardigann v5

### PR DESCRIPTION
**Pull request by bakerboy448**
reverts 6eba2fbc6a98c5363d66c1b84c0febf32180039c
reverts c8ff27ce60963230e5bbb2d028e0e2a67f2fa777
reverts 66cc961491416aa954830e10f8e48fafd7ce32f0

https://github.com/Prowlarr/Prowlarr/pull/866

### CODE REVIEW

**Comment by Qstick** [comment]
You have some in v4

**Comment by Qstick** [comment]
Moving them from v3 and v4 to v5 will mean they are no longer available for those running older versions or on dev (in case of v3). Shouldn’t we have multiple copies?

**Comment by bakerboy448** [comment]
> Moving them from v3 and v4 to v5 will mean they are no longer available for those running older versions or on dev (in case of v3). Shouldn’t we have multiple copies?

we're set now

bhd is removed per https://github.com/Jackett/Jackett/issues/12993

**Comment by Qstick** [comment]
aither is still being moved from 4 to 5, a few others as well it seems

**Review by Qstick — APPROVED** [review]

**Pull request merged**
